name: CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build
      run: 
        javac unit_0/*.java
        javac unit_1/*.java
        javac unit_2/*.java
        javac unit_3/*.java
        javac unit_4/*.java
        javac unit_5/*.java
        javac unit_6/*.java
        javac unit_7/*.java
